'use client';
import { useState } from 'react';
import type { Expense } from '../admin.types';
import { today } from '../admin.data';
import { Button } from './Primitives';
export default function ExpenseEditor({ onSave }: { onSave: (e: Expense) => void }) {
  const [monthly, setMonthly] = useState(false);
  return <form className="ad-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (!String(f.get('title')).trim()) { const input = e.currentTarget.querySelector<HTMLInputElement>('[name="title"]'); input?.setCustomValidity('Enter an expense title.'); input?.reportValidity(); return; } onSave({ id: crypto.randomUUID(), title: String(f.get('title')).trim(), category: String(f.get('category')), amount: Math.round(Number(f.get('amount')) * 100), due: String(f.get('due')), monthly, paid: f.get('paid') === 'on' ? today() : undefined }); }}><label>Expense title<input name="title" onInput={e => e.currentTarget.setCustomValidity('')} placeholder="e.g. Shop rent" required/></label><div className="ad-form-grid"><label>Category<select name="category">{['Electricity', 'Salaries', 'Raw materials', 'Shop rent', 'Machine EMI', 'Other'].map(c => <option key={c}>{c}</option>)}</select></label><label>Amount (₹)<input name="amount" type="number" min=".01" step=".01" required/></label></div><label>Due date<input name="due" type="date" defaultValue={today()} required/></label><label className="ad-checkbox"><input type="checkbox" checked={monthly} onChange={e => setMonthly(e.target.checked)}/>Repeat monthly</label>{monthly && <p className="ad-help">Creates monthly unpaid reminders with this amount. Missing reminders are generated when you open or update this demo; bills are never marked paid automatically.</p>}<label className="ad-checkbox"><input name="paid" type="checkbox"/>Already paid today</label><Button type="submit">Save expense</Button></form>;
}
