'use client';
import { useState } from 'react';
import type { Order } from '../admin.types';
import { dateLabel, money, paid, paymentStatus, total, today } from '../admin.data';
import { Badge, Empty } from './Primitives';
export default function OrderTable({ orders, onSelect, compact = false }: { orders: Order[]; onSelect: (o: Order) => void; compact?: boolean }) {
  const [page, setPage] = useState(0), pageSize = compact ? 5 : 10, last = Math.max(0, Math.ceil(orders.length / pageSize) - 1), current = Math.min(page, last);
  const rows = orders.slice(current * pageSize, (current + 1) * pageSize);
  return <>{orders.length === 0 ? <Empty/> : <div className="ad-table-wrap ad-desktop-table ad-orders-table-wrap"><table className="ad-table"><thead><tr><th>Order ID</th><th>Customer</th><th>Service</th><th>Expected delivery</th><th>Work status</th><th>Amount</th><th>Payment</th></tr></thead><tbody>{rows.map(o => <tr key={o.id}><td><button className="ad-order-link" onClick={() => onSelect(o)}>{o.id} ↗</button></td><td><strong>{o.name || 'Walk-in customer'}</strong><small>{o.phone}</small></td><td>{o.lines[0]?.name}<small>{o.lines.length > 1 ? '+' + (o.lines.length - 1) + ' more services' : o.lines[0]?.quantity + ' ' + o.lines[0]?.unit}</small></td><td>{dateLabel(o.due)}{o.status !== 'Completed' && <small className={o.due < today() ? 'ad-delivery-overdue' : ''}>{o.due < today() ? 'Overdue' : o.due === today() ? 'Due today' : 'Upcoming'}</small>}</td><td><Badge>{o.status}</Badge></td><td className="ad-number"><strong>{money(total(o))}</strong><small>{o.legacyCancelled ? 'Not collectible' : money(total(o) - paid(o)) + ' due'}</small></td><td><Badge>{paymentStatus(o)}</Badge></td></tr>)}</tbody></table></div>}{rows.length > 0 && <div className="ad-mobile-records">{rows.map(o => <button className="ad-mobile-order" key={o.id} onClick={() => onSelect(o)}><div className="ad-record-heading"><strong>{o.id} ↗</strong><strong>{money(total(o))}</strong></div><div className="ad-record-customer">{o.name || 'Walk-in customer'}<small>{o.phone}</small></div><p>{o.lines[0]?.name}{o.lines.length > 1 ? ' + ' + (o.lines.length - 1) + ' more' : ''}</p><div className="ad-record-heading"><span>Delivery {dateLabel(o.due)}{o.status !== 'Completed' && o.due <= today() ? (o.due < today() ? ' · Overdue' : ' · Today') : ''}</span><span>{o.legacyCancelled ? 'Not collectible' : money(total(o) - paid(o)) + ' balance'}</span></div><div className="ad-record-badges"><Badge>{o.status}</Badge><Badge>{o.legacyCancelled ? 'Cancelled' : paymentStatus(o)}</Badge></div></button>)}</div>}<div className="ad-pagination"><span>{orders.length ? current * pageSize + 1 : 0}–{Math.min((current + 1) * pageSize, orders.length)} of {orders.length} orders</span><div><button disabled={current === 0} onClick={() => setPage(current - 1)}>← Previous</button><button disabled={current === last} onClick={() => setPage(current + 1)}>Next →</button></div></div></>;
}
