'use client';
import { useState } from 'react';
import type { Profile as ProfileType, StorePaymentMethod } from '../admin.types';
import { Button } from './Primitives';
import PaymentMethodsSettings from './PaymentMethodsSettings';
export default function Profile({ profile: p, paymentMethods, username = 'admin', onSave, onPassword, onLogout, error }: { profile: ProfileType; paymentMethods: StorePaymentMethod[]; username?: string; onSave: (p: ProfileType) => void; onPassword: (old: string, next: string, confirm: string) => Promise<boolean>; onLogout: () => void; error: string }) {
  const [showPassword, setShowPassword] = useState(false);
  return <div className="ad-profile-grid"><section className="ad-card"><div className="ad-card-heading"><div><h2>Owner & store details</h2><p>A familiar face behind the care.</p></div><span className="ad-avatar">{p.name[0]}</span></div><form className="ad-form" onInput={e => { const field = e.target; if (field instanceof HTMLInputElement || field instanceof HTMLTextAreaElement) field.setCustomValidity(''); }} onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget);
for (const name of ['name', 'store', 'address', 'phone']) {
  const value = String(f.get(name)).trim();
  const invalid = !value || (name === 'phone' && !/^\+?[0-9]{10,15}$/.test(value.replace(/[\s()-]/g, '')));
  if (invalid) { const input = e.currentTarget.elements.namedItem(name) as HTMLInputElement; input.setCustomValidity(name === 'phone' ? 'Enter a valid phone number with 10 to 15 digits.' : 'This field cannot be blank.'); input.reportValidity(); return; }
}
onSave({ name: String(f.get('name')).trim(), phone: String(f.get('phone')).trim(), email: String(f.get('email')), store: String(f.get('store')).trim(), address: String(f.get('address')).trim() }); }}><div className="ad-form-grid"><label>Owner name<input name="name" defaultValue={p.name} required/></label><label>Username<input value={username} readOnly/></label><label>Phone<input name="phone" type="tel" pattern={'[+0-9 ()\\-]{10,18}'} title="Enter a valid phone number with 10 to 15 digits" defaultValue={p.phone} required/></label><label>Email<input name="email" type="email" defaultValue={p.email}/></label></div><label>Store name<input name="store" defaultValue={p.store} required/></label><label>Store address<textarea name="address" defaultValue={p.address} required/></label><p className="ad-help">Currency: INR · Timezone: Asia/Kolkata</p><Button type="submit">Save changes</Button></form></section><div><PaymentMethodsSettings methods={paymentMethods}/><section className="ad-card"><h2>Password & access</h2><p className="ad-help">Changing your password signs you out everywhere; sign back in with the new one.</p><form className="ad-form" onSubmit={e => { e.preventDefault(); const form = e.currentTarget; const f = new FormData(form); onPassword(String(f.get('old')), String(f.get('next')), String(f.get('confirm'))).then(ok => { if (ok) form.reset(); }); }}><label>Current password<input name="old" type={showPassword ? 'text' : 'password'} autoComplete="current-password" required/></label><label>New password<input name="next" type={showPassword ? 'text' : 'password'} autoComplete="new-password" minLength={8} required/></label><label>Confirm new password<input name="confirm" type={showPassword ? 'text' : 'password'} autoComplete="new-password" minLength={8} required/></label><label className="ad-checkbox"><input type="checkbox" checked={showPassword} onChange={e => setShowPassword(e.target.checked)}/>Show passwords</label>{error && <p className="ad-error" role="alert">{error}</p>}<Button secondary type="submit">Update password</Button></form></section><section className="ad-card ad-account-card"><h3>Done for the day?</h3><p>Sign out of your store workspace.</p><Button secondary onClick={onLogout}>Log out ↗</Button></section></div></div>;
}
