import type { PriceItem } from '@/data/pricing';
import type { Quantities } from '@/lib/pricing';
import { formatMoney } from '@/lib/pricing';

type Props = { open: boolean; weight: number; items: PriceItem[]; quantities: Quantities; total: number; whatsappHref: string; onOpen: () => void; onClose: () => void; onClear: () => void; onWeightChange: (value: number) => void; onQuantityChange: (name: string, value: number) => void };

export default function PriceCalculator({ open, weight, items, quantities, total, whatsappHref, onOpen, onClose, onClear, onWeightChange, onQuantityChange }: Props) {
  return <><button className="calculate-button" type="button" onClick={onOpen}>Calculate your price ↗</button>{open && <div className="modal-backdrop" role="presentation" onMouseDown={event => event.target === event.currentTarget && onClose()}><section className="calc-modal" role="dialog" aria-modal="true" aria-labelledby="calc-title"><header className="calc-header"><div><span>Rate-card estimate</span><h2 id="calc-title">Calculate your laundry price</h2><p>Add any combination of services. Only Wash, Dry & Fold is calculated by weight.</p></div><button type="button" onClick={onClose} aria-label="Close calculator">×</button></header><div className="calc-body"><div className="weight-card"><div><h3>Wash, Dry & Fold</h3><p>₹279 up to 4 kg · ₹379 up to 6 kg · ₹49/kg after 6 kg</p></div><label><input autoFocus type="number" min="0" max="50" step="0.5" value={weight} onChange={e => onWeightChange(Number(e.target.value))} aria-label="Laundry weight in kilograms"/><span>kg</span></label></div><p className="calc-label">Other services · quantity in pieces</p><div className="item-grid">{items.map(item => <label className="calc-item" key={item.name}><span>{item.name}<small>{item.note} · ₹{item.rate}</small></span><input type="number" min="0" max="99" value={quantities[item.name] ?? 0} onChange={e => onQuantityChange(item.name, Number(e.target.value))} aria-label={`${item.name} quantity`}/></label>)}</div></div><footer className="calc-footer"><div><span>Estimated total</span><strong aria-live="polite">{formatMoney(total)}</strong></div><button className="calc-clear" type="button" onClick={onClear}>Clear</button><a className="calc-whatsapp" href={whatsappHref} target="_blank" rel="noopener">Send estimate on WhatsApp ↗</a><p>Planning estimate only. Confirm final rates, offer eligibility, timing and pickup/delivery availability.</p></footer></section></div>}</>;
}
