import Image from 'next/image';
import Logo from '@/components/shared/Logo';
import { siteConfig, whatsappUrl } from '@/config/site';
import { priceGroups } from '@/data/pricing';
import { services } from '@/data/services';
import { ImageLightboxContainer } from '@/containers/image_lightbox';
import { NavbarContainer } from '@/containers/navbar';
import { PriceCalculatorContainer } from '@/containers/price_calculator';

function ContactButtons({ showNumber = false }: { showNumber?: boolean }) { return <div className="hero-actions"><a className="button white" href={whatsappUrl()} target="_blank" rel="noopener">Book on WhatsApp ↗</a><a className="button outline" href={siteConfig.phoneHref}>{showNumber ? siteConfig.phoneDisplay : 'Call the store'}</a></div>; }

export default function Home() {
  return <>
    <a className="skip" href="#main">Skip to content</a><NavbarContainer />
    <main id="main">
      <section className="hero" id="top"><Image className="hero-bg" src="/images/storefront.webp" alt="Express Laundry storefront in Chinnappanahalli" fill priority sizes="100vw"/><div className="hero-shade"/><div className="shell hero-content"><p className="kicker">Laundry care in Chinnappanahalli</p><h1>Fresh clothes,<br/><span>more time for you.</span></h1><div className="hero-bottom"><div><p className="hero-copy">Laundry, dry cleaning and steam ironing, handled at your neighbourhood store with doorstep pickup and delivery.</p><ContactButtons /></div><div className="hero-proof"><div><strong>5.0 ★</strong><span>19 Google reviews</span></div><div><strong>Doorstep</strong><span>Pickup & delivery</span></div><div><strong>Local</strong><span>Real neighbourhood store</span></div></div></div></div><span className="scroll-cue">Scroll to explore</span></section>
      <section className="statement" id="about"><div className="shell statement-grid"><div><h2>Laundry should give you <em>time back</em> — not another errand.</h2><p>Visit the store or arrange a doorstep pickup. We make everyday garment care simple, direct and easy to fit around your day.</p></div><div className="overlap"><div className="portrait"><Image src="/images/store-interior.webp" alt="Inside Express Laundry" fill sizes="(max-width: 900px) 80vw, 40vw"/></div><div className="detail"><Image src="/images/machines.webp" alt="Commercial laundry machines" fill sizes="(max-width: 900px) 50vw, 28vw"/></div><span>A real local facility</span></div></div></section>
      <section className="services" id="services"><div className="shell"><div className="section-head"><div><p className="eyebrow">01 — What we do</p><h2>Care for every<br/>kind of week.</h2></div><p>From the everyday wash basket to garments and household fabrics that need individual attention.</p></div><div className="service-grid">{services.map((service, index) => <article className="service" key={service.number}><span className="service-number">{service.number}</span>{index === 0 || index === 3 ? <span className="orbit"/> : null}<div><h3>{service.title[0]}<br/>{service.title[1]}</h3><p>{service.description}</p></div><span className="service-arrow">↗</span></article>)}</div></div></section>
      <section className="pricing" id="pricing"><div className="shell"><div className="section-head pricing-head"><div><p className="eyebrow">Rates displayed at our store</p><h2>Simple prices.<br/>No guesswork.</h2></div><p>The rates below are taken from the shared Express Laundry rate card. Please confirm the latest rate and offer eligibility when booking.</p></div><div className="pricing-board"><article className="price-feature"><div><span className="price-label">Wash, Dry & Fold</span><h3>Everyday laundry bundles</h3></div><div className="bundle-list">{[['Up to 4 kg','₹279'],['Up to 6 kg','₹379'],['Additional weight','₹49 / kg']].map(([name, price]) => <div className="bundle" key={name}><span>{name}</span><strong>{price}</strong></div>)}</div></article>{priceGroups.map(group => <div className="price-detail" key={group.title}><h3>{group.title}</h3>{group.items.map(item => <div className="price-line" key={item.name}><span>{item.name}<small>{item.note}</small></span><strong>₹{item.rate}</strong></div>)}{group.title === 'Optional add-ons' && <div className="offer"><span>Store offer<small>Confirm eligibility and applicable services</small></span><strong>10% off</strong></div>}</div>)}</div><div className="pricing-footer"><p><strong>Free home delivery and delivery within 24 hours are advertised on the store rate card.</strong> Availability and conditions may vary; confirm while booking.</p><div className="pricing-actions"><PriceCalculatorContainer/><ImageLightboxContainer/></div></div></div></section>
      <section className="inside" id="inside"><div className="shell inside-layout"><div className="inside-copy"><p className="kicker">Inside Express Laundry</p><h2>A real store.<br/>Real equipment.<br/>Local care.</h2><p className="inside-intro">Our Chinnappanahalli facility is equipped for washing, drying and steam ironing, with a team you can contact directly.</p><div className="inside-facts"><div><strong>Commercial equipment</strong><small>For everyday laundry</small></div><div><strong>Direct support</strong><small>Call or WhatsApp</small></div><div><strong>Doorstep service</strong><small>Pickup & delivery available</small></div><div><strong>Local address</strong><small>Friends Layout</small></div></div></div><div className="inside-visual"><span className="inside-index" aria-hidden="true">01</span><Image className="inside-main" src="/images/ironing-stations.webp" alt="Steam ironing stations at Express Laundry" width={800} height={800}/><Image className="inside-small" src="/images/machines.webp" alt="Commercial washing and drying machines" width={400} height={300}/><Image className="inside-room" src="/images/store-interior.webp" alt="Full interior of the store" width={400} height={300}/><Image className="inside-front" src="/images/storefront-secondary.webp" alt="Express Laundry storefront" width={800} height={300}/></div></div></section>
      <section className="location" id="location"><div className="shell location-card"><div className="location-copy"><p className="eyebrow">05 — Find the store</p><h2>Near you in<br/>Friends Layout.</h2><address><strong>{siteConfig.name}</strong>{siteConfig.address.map(line => <span key={line}>{line}<br/></span>)}</address><a className="button blue" href={siteConfig.mapsUrl} target="_blank" rel="noopener">Open Google Maps ↗</a></div><iframe title="Express Laundry location on Google Maps" src={siteConfig.mapEmbedUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></div></section>
      <section className="cta"><div className="shell cta-inner"><div><Logo/><h2>Make laundry<br/>the easy part.</h2></div><ContactButtons showNumber/></div></section>
    </main>
    <footer><div className="shell footer-inner"><a href="#top"><Logo/></a><p>© {new Date().getFullYear()} Express Laundry</p><span>Laundry · Dry cleaning · Steam ironing</span><a href="#top">Back to top ↑</a></div></footer>
    <div className="mobile-actions"><a href={siteConfig.phoneHref}>Call</a><a href={whatsappUrl()} target="_blank" rel="noopener">Book on WhatsApp</a></div>
  </>;
}
